### ISSUE TITLE
UI/UX further enhancements are needed

### ISSUE THREAD

**Issue by nivindulakshitha** [Ict-project-2024/Frontend#64]
Hence, students who are not registered with the system can enter the library and MC, UI/UX should take care of them to obtain their phone numbers because of library and MC checking-in operations should have both TE number and phone number.

**Comment by YuklidD** [comment]
Registration must be compulsory for the system who are registered to the MC and library. So no need of retaking phone numbers. What is your idea?

**Comment by nivindulakshitha** [comment]
While we are not enforcing the community to register with the system, Library and MC do need to keep their logs about every student. By the other hand Library has its own student registration procedure but MC does not.

**Comment by nivindulakshitha** [comment]
This issue concludes as "Students have to be registered with the system in order to enter to either Library or MC" for now.
